### Environment Management with Conda and renv
Most genomics analyses are conducted with a combination of R and Python, each with its own ecosystem of packages and dependencies. To manage these dependencies and ensure reproducibility, we urge you to use environment management tools like [Conda](/pages/resources/conda.qmd) for Python and [renv](/pages/resources/renv.qmd) for R. Before you start coding, take some time to set up your environment with the necessary packages and dependencies. This will save you time and headaches down the line when you need to reproduce your analysis or share it with collaborators.

### Working with the Caltech HPC
Genomics workflows can be computationally intensive. For this reason, you may want to run your analyses on the Caltech High Performance Computing (HPC) cluster, which provides access to powerful computing resources and specialized software. However, working on the HPC can be a bit daunting for new users. We recommend familiarizing yourself with the HPC environment and its job scheduling system (Slurm) before you start running your analyses with our [HPC tutorial](/pages/resources/hpc/HPC.qmd). This will help you avoid common pitfalls and make the most of the resources available to you.